---
name: Functional tests (Local)

on: # yamllint disable-line rule:truthy
  pull_request: {}
  push:
    branches:
      - "main"

defaults:
  run:
    shell: sh

jobs:
  functional-tests:
    name: Functional tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - uses: ./
        id: pascal
        with:
          path: ./HelloWorld.pas
      - name: Validate result
        run: |
          [ "Hello World!" = "${{ steps.pascal.outputs.result }}" ] || exit 1;
