---
name: Functional tests (Local)

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:

jobs:
  functional_tests:
    name: Functional tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: pascal
        with:
          path: ./HelloWorld.pas
      - name: Validate result
        run: |
          [[ "Hello World!" == "${{ steps.pascal.outputs.result }}" ]] || exit 1;
