---
name: Functional tests

on:
  push:
    branches:
      - main
      - 'bugfix/**'
      - 'feature/**'

jobs:
  functional_tests:
    name: Functional tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./
        id: pascal
        with:
          path: ./HelloWorld.pas
      - name: Validate result
        run: |
          [[ "Hello World!" == "${{ steps.pascal.outputs.result }}" ]] || exit 1;
