---
name: Functional tests (Remote)

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"

defaults:
  run:
    shell: sh

jobs:
  functional-tests-remote:
    name: Functional tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Run Pascal script
        uses: fabasoad/pascal-action@main
        id: pascal
        with:
          path: ./HelloWorld.pas
      - name: Validate result
        run: |
          [ "Hello World!" = "${{ steps.pascal.outputs.result }}" ] || exit 1;
