---
name: Functional tests (Remote)

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"

jobs:
  functional-tests:
    name: Functional tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fabasoad/pascal-action@main
        id: pascal
        with:
          path: ./HelloWorld.pas
      - name: Validate result
        run: |
          [[ "Hello World!" == "${{ steps.pascal.outputs.result }}" ]] || exit 1;
